name: ${project.name}
version: ${project.version}
api-version: 1.16
main: ${project.groupId}.${project.artifactId}.${project.name}
author: WitheredToast
commands:
  duels:
    usage: "/<command>"
    description: "Admin duels command"
    aliases: [ ]